#!/bin/bash
# Ensure that the script terminates if it receives SIGINT.
function finish {
  exit 0
}

# Run the PHP-FPM daemon in the foreground.
status=$(/etc/init.d/php7.3-fpm status)

if [[ $? != 0 ]]; then
  exec > >(logger -p user.info) 2> >(logger -p user.warn)
  exec "/usr/sbin/php-fpm7.3" \
    -c "/etc/php/7.3/fpm/php.ini" \
    -y "/etc/php/7.3/fpm/php-fpm.conf" \
    -F \
    -R
else
  trap finish SIGINT

  while :; do
    sleep 1
    echo "PHP-FPM not ready"
  done
fi